In [1]:
!pip install transformers accelerate --upgrade


In [3]:
!pip install transformers accelerate


In [5]:
!pip install huggingface_hub[hf_xet]


   ---------------------------------------- 0.0/4.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.2 MB ? eta -:--:--
    --------------------------------------- 0.1/4.2 MB 871.5 kB/s eta 0:00:05
    --------------------------------------- 0.1/4.2 MB 871.5 kB/s eta 0:00:05
   -- ------------------------------------- 0.2/4.2 MB 1.1 MB/s eta 0:00:04
   -- ------------------------------------- 0.2/4.2 MB 1.1 MB/s eta 0:00:04
   -- ------------------------------------- 0.2/4.2 MB 1.1 MB/s eta 0:00:04
   --- ------------------------------------ 0.4/4.2 MB 1.3 MB/s eta 0:00:03
   --- ------------------------------------ 0.4/4.2 MB 1.3 MB/s eta 0:00:03
   --- ------------------------------------ 0.4/4.2 MB 1.3 MB/s eta 0:00:03
   --- ------------------------------------ 0.4/4.2 MB 1.3 MB/s eta 0:00:03
   -------- ------------------------------- 0.9/4.2 MB 1.7 MB/s eta 0:00:03
   -------- -----------------

In [7]:
from huggingface_hub import login
login(token="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")  # Get it from https://huggingface.co/settings/token


In [9]:
from transformers import pipeline, AutoModelForCausalLM, AutoTokenizer
import torch


In [11]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, AutoModelForCausalLM, pipeline

def load_model_pipeline(model_id, task="text-generation", max_length=256):
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    
    if task == "text2text-generation":
        model = AutoModelForSeq2SeqLM.from_pretrained(model_id)
    else:
        model = AutoModelForCausalLM.from_pretrained(model_id)

    return pipeline(task, model=model, tokenizer=tokenizer, max_length=max_length)

# Falcon-RW-1B (text-generation model)
falcon_pipeline = load_model_pipeline("tiiuae/falcon-rw-1b", task="text-generation")

# FLAN-T5 Base (text2text generation)
flan_pipeline = load_model_pipeline("google/flan-t5-base", task="text2text-generation")

# Optional: Dolly for comparison (can be slow)
dolly_pipeline = load_model_pipeline("databricks/dolly-v2-3b", task="text-generation")


model.safetensors:  72%|#######1  | 1.88G/2.62G [00:00<?, ?B/s]

Device set to use cpu
Device set to use cpu


pytorch_model.bin:  11%|#         | 598M/5.68G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/5.68G [00:00<?, ?B/s]

Device set to use cpu


In [13]:
#prompt = "Explain the importance of clean energy in simple terms."Falcon output"
print("Falcon Response:")
print(falcon_pipeline(prompt)[0]['generated_text'])

# FLAN-T5 output
print("\nFLAN-T5 Response:")
print(flan_pipeline(prompt)[0]['generated_text'])

# Dolly output
print("\nDolly Response:")
print(dolly_pipeline(prompt)[0]['generated_text'])prompt = "Explain the importance of clean energy in simple terms."



Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Falcon Response:


Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


Explain the importance of clean energy in simple terms.
The importance of clean energy is that it is a renewable source of energy. It is a source of energy that is not limited by the availability of fossil fuels. It is a source of energy that is not limited by the availability of water. It is a source of energy that is not limited by the availability of land. It is a source of energy that is not limited by the availability of minerals. It is a source of energy that is not limited by the availability of metals. It is a source of energy that is not limited by the availability of other resources. It is a source of energy that is not limited by the availability of other energy sources. It is a source of energy that is not limited by the availability of other energy sources. It is a source of energy that is not limited by the availability of other energy sources. It is a source of energy that is not limited by the availability of other energy sources. It is a source of energy that is not li

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


clean energy is a renewable energy source

Dolly Response:
Explain the importance of clean energy in simple terms.

Clean energy is a growing industry that will power the world for decades to come. It's a proven technology that reduces carbon emissions and is a good source of jobs. It's also a smart investment because it reduces your reliance on fossil fuels, which are known to be harmful to the environment.

Clean energy is a growing industry that will power the world for decades to come. It's a proven technology that reduces carbon emissions and is a good source of jobs. It's also a smart investment because it reduces your reliance on fossil fuels, which are known to be harmful to the environment.

Clean energy is a growing industry that will power the world for decades to come. It's a proven technology that reduces carbon emissions and is a good source of jobs. It's also a smart investment because it reduces your reliance on fossil fuels, which are known to be harmful to the environ

In [15]:
def compare_models(prompt):
    print("Prompt:", prompt)

    print("\nFalcon:")
    print(falcon_pipeline(prompt)[0]['generated_text'])

    print("\nFLAN-T5:")
    print(flan_pipeline(prompt)[0]['generated_text'])

    print("\nDolly:")
    print(dolly_pipeline(prompt)[0]['generated_text'])

# Example usage
compare_models("How does a solar panel work?")


Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


Prompt: How does a solar panel work?

Falcon:
How does a solar panel work?
A solar panel is a device that converts sunlight into electricity. It is a device that converts the energy of the sun into electricity.
How does a solar panel work?
A solar panel is a device that converts sunlight into electricity. It is a device that converts the energy of the sun into electricity.
How does a solar panel work?
A solar panel is a device that converts sunlight into electricity. It is a device that converts the energy of the sun into electricity.
How does a solar panel work?
A solar panel is a device that converts sunlight into electricity. It is a device that converts the energy of the sun into electricity.
How does a solar panel work?
A solar panel is a device that converts sunlight into electricity. It is a device that converts the energy of the sun into electricity.
How does a solar panel work?
A solar panel is a device that converts sunlight into electricity. It is a device that converts the 

In [11]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# Define the categories (adjusted to 4 classes)
categories = ['Energy', 'Solar Power', 'Clean Energy', 'Environment']

# True categories for generated content (manually assigned or from ground truth)
true_labels = ['Clean Energy', 'Solar Power', 'Clean Energy', 'Energy', 'Environment']

# Model predictions (simulated or based on model outputs)
# Here, we simulate this by manually assigning categories to the generated text.
falcon_predictions = ['Clean Energy', 'Energy', 'Clean Energy', 'Energy', 'Environment']
flan_predictions = ['Solar Power', 'Solar Power', 'Technology', 'Energy', 'Environment']  # "Technology" is invalid
dolly_predictions = ['Clean Energy', 'Solar Power', 'Clean Energy', 'Technology', 'Energy']  # "Technology" is invalid

# Convert category labels to numerical labels
label_map = {category: idx for idx, category in enumerate(categories)}

# Function to handle invalid predictions
def map_to_valid_category(predictions):
    return [label if label in label_map else 'Energy' for label in predictions]  # Defaulting invalid to 'Energy'

true_labels_numeric = [label_map[label] for label in true_labels]
falcon_predictions_numeric = [label_map[label] for label in falcon_predictions]
flan_predictions_numeric = [label_map[label] for label in map_to_valid_category(flan_predictions)]
dolly_predictions_numeric = [label_map[label] for label in map_to_valid_category(dolly_predictions)]

# Confusion Matrix and Classification Report for Falcon
print("Confusion Matrix for Falcon:")
falcon_cm = confusion_matrix(true_labels_numeric, falcon_predictions_numeric, labels=[0, 1, 2, 3])
print(falcon_cm)
print("\nClassification Report for Falcon:")
print(classification_report(true_labels_numeric, falcon_predictions_numeric, target_names=categories, labels=[0, 1, 2, 3]))

# Confusion Matrix and Classification Report for FLAN-T5
print("\nConfusion Matrix for FLAN-T5:")
flan_cm = confusion_matrix(true_labels_numeric, flan_predictions_numeric, labels=[0, 1, 2, 3])
print(flan_cm)
print("\nClassification Report for FLAN-T5:")
print(classification_report(true_labels_numeric, flan_predictions_numeric, target_names=categories, labels=[0, 1, 2, 3]))

# Confusion Matrix and Classification Report for Dolly
print("\nConfusion Matrix for Dolly:")
dolly_cm = confusion_matrix(true_labels_numeric, dolly_predictions_numeric, labels=[0, 1, 2, 3])
print(dolly_cm)
print("\nClassification Report for Dolly:")
print(classification_report(true_labels_numeric, dolly_predictions_numeric, target_names=categories, labels=[0, 1, 2, 3]))


Confusion Matrix for Falcon:
[[1 0 0 0]
 [1 0 0 0]
 [0 0 2 0]
 [0 0 0 1]]

Classification Report for Falcon:
              precision    recall  f1-score   support

      Energy       0.50      1.00      0.67         1
 Solar Power       0.00      0.00      0.00         1
Clean Energy       1.00      1.00      1.00         2
 Environment       1.00      1.00      1.00         1

    accuracy                           0.80         5
   macro avg       0.62      0.75      0.67         5
weighted avg       0.70      0.80      0.73         5


Confusion Matrix for FLAN-T5:
[[1 0 0 0]
 [0 1 0 0]
 [1 1 0 0]
 [0 0 0 1]]

Classification Report for FLAN-T5:
              precision    recall  f1-score   support

      Energy       0.50      1.00      0.67         1
 Solar Power       0.50      1.00      0.67         1
Clean Energy       0.00      0.00      0.00         2
 Environment       1.00      1.00      1.00         1

    accuracy                           0.60         5
   macro avg      

C:\Users\Pooja\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Pooja\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Pooja\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Pooja\anaconda3\Lib\site-packag